### ISSUE TITLE
File extensions are case-sensitive and may not work

### ISSUE THREAD

**Issue by uellue** [matbryan52/image-viewer#16]
Example: https://moellenstedt.iff.kfa-juelich.de/user-redirect/image-viewer/?path=/storage/er-c-data%2Fadhoc%2Fspectra-microscope%2F2022-08-11-SAT%2Fraw%2FTEM%2F300Kv%2F3+Spotdrift%2Fmeasured+10min+0.25nm+min.JPG

**Comment by matbryan52** [comment]
Took a while for me to remember but I think this is now fixed with https://github.com/matbryan52/image-viewer/commit/7562492096c08cc2dcad73579ac8d6a4bcab7f61

Sorry it slipped through!

**Comment by sk1p** [comment]
Confirmed fixed, thanks!
