### ISSUE TITLE
Multi-channel support: select "nav" / "sig" axes

### ISSUE THREAD

**Issue by sk1p** [matbryan52/image-viewer#3]
`rsciio` gives us a description of the axes, as a list of dicts, that looks something like this:

```python
[{'name': 'z', 'size': 20, 'index_in_array': 0, 'scale': 1.0, 'offset': -0.0, 'units': '', 'navigate': True},
{'name': 'y', 'size': 3838, 'index_in_array': 1, 'scale': 0.1671157330274582, 'offset': -0.0, 'units': 'nm', 'navigate': False},
{'name': 'x', 'size': 3710, 'index_in_array': 2, 'scale': 0.1671157330274582, 'offset': -0.0, 'units': 'nm', 'navigate': False}]
```

(inspect `result['axes']` in `load_rsciio`)

In this case, the data is of shape `(20, 3838, 3710)`. The correct behavior would be to have 20 channels of size `(3838, 3710)`, but currently, there are 3710 channels instead.

At least for `rsciio`-loaded data, could we use the axes information to automatically select the 'x', 'y' channels as "sig" (they have `navigate=False` set), and the remaining one for the slider?

In this particular case, I could get it to work using the following patch, but that's not generally applicable of course:

```diff
diff --git a/src/image_viewer/app.py b/src/image_viewer/app.py
index 0adcdb0..2bbf2b5 100644
--- a/src/image_viewer/app.py
+++ b/src/image_viewer/app.py
@@ -40,7 +40,7 @@ def viewer():
 """)
 
     figure = ApertureFigure.new(
-        array,
+        list(array),
         title=meta.get('title', None),
     )
     return pn.Column(
```

**Comment by matbryan52** [comment]
I actually added a parameter upstream to select the slicing dimension in the case of a 3D numpy array, by default it is -1.

```python
     figure = ApertureFigure.new(
         array,
         title=meta.get('title', None),
         channel_dimension=0,
     )
```

would do the job here I think.


https://github.com/LiberTEM/LiberTEM-panel-ui/blob/04c00e0ea3a64cc1b7bf67f752133fb857195ed5/src/libertem_ui/live_plot.py#L114


If the data was 4D we can use something like:

```python
### apply np.transpose to choose put nav dims first
import libertem.api as lt
ctx = lt.Context.make_with('inline')
ds = ctx.load('memory', data=data)
from libertem_ui.windows.imaging import VirtualDetectorWindow
detector_window = VirtualDetectorWindow.using(ctx, ds)
detector_window.layout().servable()
```

rather than creating our own layout with a Figure etc.

**Comment by matbryan52** [comment]
If it's necessary to let the user decide which axes are the nav dims they want it would not be much work to add an interstitial page with some widgets to do that...

**Comment by matbryan52** [comment]
Another possibility which is not much work - the above snippet uses a `VirtualDetectorWindow` because it's already done, it's only as a side effect you get frame picking for preview - but the baseclass could be made concrete into a `PickFrameWindow` without the analyses. As a bonus we could also implement the ability to preview 3D-STEM-EELS-like data (2-nav 1-sig) if that is of interest.

**Comment by sk1p** [comment]
> I actually added a parameter upstream to select the slicing dimension in the case of a 3D numpy array, by default it is -1.

Ah, yeah, that would work for 3D stacks, indeed! The approach in #4 also supports more than one navigation dimension, which are then basically flattened (but it should also support something strange like `(nav1, sig1, nav2, sig2)`, which is expressable by the axis description returned by rosettasciio). 

Please feel to close #4 - I can work on the version that sets `channel_dimension` instead — let me know how we should coordinate this. I think we will need special support for >3D data anyways (example: if we see performance issues, we may want to use either lazy arrays in these cases, or just straight up LiberTEM, if it is a supported file format).

> If the data was 4D we can use something like: [...]
> As a bonus we could also implement the ability to preview 3D-STEM-EELS-like data (2-nav 1-sig) if that is of interest.

For now, support for 2D images and stacks thereof is most important, but EELS cube support would indeed be very nice!

**Comment by matbryan52** [comment]
> Ah, yeah, that would work for 3D stacks, indeed! The approach in #4 also supports more than one navigation dimension, which are then basically flattened (but it should also support something strange like `(nav1, sig1, nav2, sig2)`, which is expressable by the axis description returned by rosettasciio).

In this case we could accept:

```python
channel_dimension=(0, 2)
```
and the `np.ndindex` semantics could be handled on the fly, no need to copy the data?? The result remains a flat index into a stack, but we could at least show the real slice in the figure title.

**Comment by sk1p** [comment]
> In this case we could accept: [...]

That would be nice indeed!

> and the np.ndindex semantics could be handled on the fly, no need to copy the data?? The result remains a flat index into a stack, but we could at least show the real slice in the figure title.

:+1:
