### ISSUE TITLE
Required Python version for deployment?

### ISSUE THREAD

**Issue by sk1p** [matbryan52/image-viewer#6]
What's the minimum supported Python version?

I think because of the new-style lowercase type annotations (like `dict[str,int]`) that would be around 3.10, correct?  If we wanted to support older Python, we would need `from __future__ import annotations`?

**Comment by matbryan52** [comment]
I think 3.9 ? : https://peps.python.org/pep-0585/

That said, I've made use of `from __future__ import annotations` in `LiberTEM-panel-ui` so I can add the same to this repo. That should bring it down to about 3.7 ? (as long as the install is reasonably recent)

**Comment by matbryan52** [comment]
I do think the type Union syntax `int | None` is from 3.10, you're right! Still should be fine with `__future__` though.

**Comment by sk1p** [comment]
> That should bring it down to about 3.7

Correct.

**Comment by matbryan52** [comment]
Closed through #4 (drive-by)
