### ISSUE TITLE
Deployment: environment, token auth

### ISSUE THREAD

**Issue by sk1p** [matbryan52/image-viewer#7]
In deployment, it may make sense to separate the actual image viewer from the proxy config, as you may not want to install the image viewer dependencies into the same environment as jupyterhub itself. Would that be possible, maybe by having separate Python packages?

Also, in our scenario, it's running on a multi-user system, is it possible to constrain the `panel serve` port to the specific unix user, maybe by having a token, similar to what we did in https://github.com/LiberTEM/LiberTEM-jupyter-proxy?

**Comment by matbryan52** [comment]
> In deployment, it may make sense to separate the actual image viewer from the proxy config, as you may not want to install the image viewer dependencies into the same environment as jupyterhub itself. Would that be possible, maybe by having separate Python packages?

Definitely - this repo was structured mainly to make it easily deployable on Binder, but given the 'app' is only the two files under src/ it could be restructured however. We can start by deleting everything that is there just for Binder...

> Also, in our scenario, it's running on a multi-user system, is it possible to constrain the `panel serve` port to the specific unix user, maybe by having a token, similar to what we did in https://github.com/LiberTEM/LiberTEM-jupyter-proxy?

I think everything you need is available (see https://panel.holoviz.org/how_to/authentication/index.html) but I'm not very familiar with the reality of Panel authentication as I've never had a need to use it. I will have a read and see what I can suggest.

**Comment by matbryan52** [comment]
A few thoughts:

- The actual user session (session == the page + state being served to the user) is token-protected by default. I can't access someone else's session unless I know their token. As far as I can see this token is generated when the session is created and is added into the URL-path (as with Jupyter). Without extra authentication anyone who connects to an endpoint gets a new token + session.
- I'm assuming that in your deployment the `panel serve` command will be launched in the name of the user, rather than as an actual central / service account or container ? On the basis that this means file access permissions are zero-effort.
- If you want to restrict the particular instance of `panel serve` to a user we could use their callback mechanism : https://panel.holoviz.org/how_to/authentication/authorization.html. This runs a python function on session creation to provide a go / no-go. The detail would be how to pass some kind of secret into the `panel serve` command so that the callback could verify against it. I feel like the right way to do that is use their OAuth integrations, but I don't know if that's feasible in your case?

**Comment by sk1p** [comment]
Thanks for #8 - that's _almost_ working :) In the current implementation, it's still required to have the `image_viewer` module available in the environment (and panel). I can whip up a PR to make this configurable.

My idea was similar to how we solved this in libertem-jupyter-proxy:

https://github.com/LiberTEM/LiberTEM-jupyter-proxy/blob/6e2d8153c6b2abc5bba914c064d665cc30c5117d/libertem_jupyter_proxy/__init__.py#L14

We put a JSON config file into the jupyterhub venv under `$venv_prefix/etc/` and pull the full path to `libertem-server` from it, which is installed in a completely different venv.

In this case, I would suggest we first try to import `image_viewer`, and if that doesn't work, try to get the path via some configuration. Would that work for you, too?

> * I'm assuming that in your deployment the `panel serve` command will be launched in the name of the user, rather than as an actual central / service account or container ? On the basis that this means file access permissions are zero-effort.

Exactly - we are using JupyterHub for auth{z,n}.

> If you want to restrict the particular instance of panel serve to a user we could use their callback mechanism : https://panel.holoviz.org/how_to/authentication/authorization.html. This runs a python function on session creation to provide a go / no-go.

Ok, in principle this is a good approach, but...

> The detail would be how to pass some kind of secret into the panel serve command so that the callback could verify against it.

Exactly... can we access HTTP headers from this authorization function?

>I feel like the right way to do that is use their OAuth integrations, but I don't know if that's feasible in your case?

Yeah, not really feasible sadly (we don't want the user to need both the jupyter auth and then afterwards the panel auth) - basically, we need a way to distinguish requests that come in via the jupyterhub proxy from those fired directly against the port where `panel serve` is listening. For example, the proxy can add a header to include a token in each request, like here:

https://github.com/LiberTEM/LiberTEM-jupyter-proxy/blob/6e2d8153c6b2abc5bba914c064d665cc30c5117d/libertem_jupyter_proxy/__init__.py#L87-L89

If we can convince panel to compare the token in the header to a token given via a file, that would solve the issue. I'll have a look at how the auth stuff is implemented in panel...

**Comment by matbryan52** [comment]
> Thanks for https://github.com/matbryan52/image-viewer/pull/8 - that's almost working :) In the current implementation, it's still required to have the image_viewer module available in the environment (and panel). I can whip up a PR to make this configurable.

I figured there would always be site-specific config so the `proxy_config` implementation here was just a fallback. Feel free to modify it, or I can write something that looks for a JSON.

> In this case, I would suggest we first try to import image_viewer, and if that doesn't work, try to get the path via some configuration. Would that work for you, too?

Of course! This whole project is really just for you guys so change / implement whatever you like.

As for auth:

https://panel.holoviz.org/how_to/state/request.html

should have the HTTP headers available inside.

It also seems they implement the URL args parsing that I manually implemented here, I will see if I can replace with their implem.

**Comment by matbryan52** [comment]
>My idea was similar to how we solved this in libertem-jupyter-proxy:

> https://github.com/LiberTEM/LiberTEM-jupyter-proxy/blob/6e2d8153c6b2abc5bba914c064d665cc30c5117d/libertem_jupyter_proxy/__init__.py#L14

> We put a JSON config file into the jupyterhub venv under $venv_prefix/etc/ and pull the full path to libertem-server from it, which is installed in a completely different venv.

After having a read through the LT-proxy implementation I agree we can take the same approach here. Unless you've already started on this I will make a PR ?

**Comment by matbryan52** [comment]
This branch https://github.com/matbryan52/image-viewer/compare/main...deploy-auth might do the job ? It's a direct adaptation from `LiberTEM-jupyter-proxy`. I implemented an entrypoint `image-viewer` to simplify finding the app on the PATH as the fallback.

Testing locally my connection to the app is rejected if I don't go via the proxied address (i.e. the `X-Api-Key` is not in the headers).

**Comment by sk1p** [comment]
> Unless you've already started on this I will make a PR ?

I had started to experiment with the `authorize` approach, but hadn't gotten as far as you. Your branch looks good, there's only one issue that I also hit yesterday: the `authorize` function is run _after_ the `viewer` function.

Apparently, if I understand the way panel works correctly, for each user session, the given "app module" is run. In our case, that already loads data etc. I think we somehow need to wait with loading data until the authorization is finished. Is there a "lifecycle event" of some kind, so that the main code only runs once the "initialization" (?) is done?

**Comment by sk1p** [comment]
> there's only one issue that I also hit yesterday: the `authorize` function is run _after_ the `viewer` function

I think this relates to the authentication/authorization split - panel assumes authentication is sufficient to start the session, before authorization. I'll check how easy it is to build a simple `AuthProvider` instead.

**Comment by matbryan52** [comment]
> there's only one issue that I also hit yesterday: the authorize function is run after the viewer function.

Oh no! Two ways to work around this that I can see:

https://panel.holoviz.org/how_to/callbacks/session.html#pn-state-on-session-created actually runs before `viewer()`, so we can hook in here.

Alternatively we can actually delay loading the data / displaying the image until the page has fully loaded:

https://panel.holoviz.org/how_to/callbacks/load.html#defer-a-task

which might actually be a better user experience as the page will load in and the data arrives a few seconds later (good for large datasets!).

What do you think?

**Comment by matbryan52** [comment]
> Alternatively we can actually delay loading the data / displaying the image until the page has fully loaded:

I implemented this on the branch, no data is loaded in the case we fail the auth check.

**Comment by sk1p** [comment]
> > Alternatively we can actually delay loading the data / displaying the image until the page has fully loaded:
> 
> I implemented this on the branch, no data is loaded in the case we fail the auth check.

Yeah, I think that's a good solution - I tried to go the `AuthProvider` route, and it was a bit unclear how that works in the beginning: https://github.com/matbryan52/image-viewer/compare/deploy-auth...sk1p:image-viewer:my-token-auth

Loading the data "lazily" is much better, to give the user at least some feedback that something is happening. I like it!

**Comment by matbryan52** [comment]
Hijacking this for security topics:

- Need to remove load from URL
- Is it problematic that this could be used to load files using relative paths to climb out of the directory? (we allow this in libertem-server)

**Comment by sk1p** [comment]
> * Need to remove load from URL

:+1:

> * Is it problematic that this could be used to load files using relative paths to climb out of the directory? (we allow this in libertem-server)

Normally not problematic - only scenario I can think of is if you give someone a link to a weird/broken/"adversarial" file, and the other user clicks on it - but in our case, the bad actor can just put the same file directly into the data management instead, if they can write such a file to the server somewhere.

In `libertem-server` we only `detect` on such paths, and don't fully load it without user confirmation.

In the long run, it might make sense to sandbox this service more, possibly by running it in a container with a strong seccomp filter, and importantly read-only bind-mounting the data. But that would need a different spawner, too... (kubernetes maybe?)
